codecov:
  token: e3b40abf-e5d2-4a47-ac19-bc2d5cee6bfe
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true


# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
